# Generated by Django 5.2.17 on 2026-10-05 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0025_alter_exchangerateservice_service_type'),
        ('import_app', '0002_alter_importprofile_name_and_more'),
        ('transactions', '0050_filterpreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(help_text='Global ordering of the row within the run')),
                ('section', models.CharField(blank=True, default='', help_text='Source section (file name, sheet name, zip member)', max_length=10000)),
                ('row_number', models.IntegerField(help_text='Row number inside the source section')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Stable key derived from the source file and row', max_length=64)),
                ('raw_payload', models.JSONField(default=dict, help_text='Raw values extracted from the source file')),
                ('mapped_payload', models.JSONField(blank=True, help_text='Mapped, JSON-serializable values ready to be committed', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STAGED', 'Staged'), ('COMMITTED', 'Committed'), ('SKIPPED', 'Skipped'), ('FAILED_RETRYABLE', 'Failed (retryable)'), ('FAILED_PERMANENT', 'Failed (permanent)')], default='PENDING', max_length=20, verbose_name='Status')),
                ('failure_reason', models.JSONField(blank=True, help_text='Structured failure reason: {stage, code, message, line, exception}', null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('committed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='importrun',
            name='config_snapshot',
            field=models.TextField(blank=True, default='', help_text='YAML configuration snapshot taken at enqueue time'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='cursor',
            field=models.JSONField(blank=True, default=dict, help_text='Persistent resume cursor'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA-256 hash of the source file content', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='importrun',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='Source file size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='importrun',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, help_text='Time at which the current lease expires', null=True),
        ),
        migrations.AddField(
            model_name='importrun',
            name='lease_owner',
            field=models.CharField(blank=True, help_text='Identifier of the worker owning the current lease', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='importrun',
            name='mode',
            field=models.CharField(choices=[('strict', 'Strict'), ('fault_tolerant', 'Fault tolerant')], default='strict', max_length=20, verbose_name='Mode'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='phase',
            field=models.CharField(choices=[('enqueued', 'Enqueued'), ('parsing', 'Parsing'), ('committing', 'Committing'), ('finished', 'Finished'), ('failed', 'Failed')], default='enqueued', max_length=20, verbose_name='Phase'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='retryable_rows',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importrun',
            name='run_attempts',
            field=models.IntegerField(default=0, help_text='How many times the processing task was (re)started'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='source_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Summary of the parsed source (sections, row counts, ...)'),
        ),
        migrations.AddField(
            model_name='importrun',
            name='stored_file_path',
            field=models.CharField(blank=True, default='', help_text='Absolute path of the staged source file (server side)', max_length=10000),
        ),
        migrations.AddConstraint(
            model_name='importrun',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['QUEUED', 'PROCESSING'])), fields=('profile', 'file_hash'), name='uniq_active_run_profile_filehash'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='import_app.importrun'),
        ),
        migrations.AddField(
            model_name='importrow',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Transaction produced when this row was committed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='transactions.transaction'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['run', 'status'], name='import_app__run_id_daee00_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='uniq_importrow_run_sequence'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('run', 'idempotency_key'), name='uniq_importrow_run_idempotency_key'),
        ),
    ]
