# Generated by Django 5.2.17 on 2026-10-05 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_app', '0003_importrow_importrun_config_snapshot_importrun_cursor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='User who enqueued the run; used for recovered retries', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_runs', to=settings.AUTH_USER_MODEL),
        ),
    ]
